### PR TITLE
add image-transition blog post resources

### PR DESCRIPTION
**Pull request by wunmi-adb**

### CODE REVIEW

**Review by simeoncarstens — COMMENTED** [review]
I tried running this, but after an `npx expo start --web --offline`, the page that opens in the browser is empty and the JavaScript console shows the following error. It's well possible that I didn't set this up correctly, I have no JavaScript / React / ... experience. Could you try running this with a clean checkout of this branch and see whether it works fine on your end?
```
AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:37437 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:277 Uncaught TypeError: Cannot read properties of undefined (reading 'RuntimeEffect')
    at JsiSkRuntimeEffectFactory.Make (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:97068:33)
    at AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:153200:69
    at loadModuleImplementation (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:260:7)
    at guardedLoadModule (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:169:14)
    at metroRequire (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:87:75)
    at AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:59013:22
    at loadModuleImplementation (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:260:7)
    at guardedLoadModule (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:169:14)
    at metroRequire (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:87:75)
    at AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:625:37

```

**Comment by wunmi-adb** [comment]
> I tried running this, but after an `npx expo start --web --offline`, the page that opens in the browser is empty and the JavaScript console shows the following error. It's well possible that I didn't set this up correctly, I have no JavaScript / React / ... experience. Could you try running this with a clean checkout of this branch and see whether it works fine on your end?
> 
> ```
> AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:37437 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
> AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:277 Uncaught TypeError: Cannot read properties of undefined (reading 'RuntimeEffect')
>     at JsiSkRuntimeEffectFactory.Make (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:97068:33)
>     at AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:153200:69
>     at loadModuleImplementation (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:260:7)
>     at guardedLoadModule (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:169:14)
>     at metroRequire (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:87:75)
>     at AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:59013:22
>     at loadModuleImplementation (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:260:7)
>     at guardedLoadModule (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:169:14)
>     at metroRequire (AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:87:75)
>     at AppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:625:37
> ```

Seems like you're trying to run this on the web and this was originally built for mobile, I will attach a ReadMe file to show steps on how you can run on your mobile

**Comment by wunmi-adb** [comment]
@simeoncarstens I have added the readme file, please let me know if you still encounter any issues.

**Comment by simeoncarstens** [comment]
@theresasogunle thanks, that was very helpful :slightly_smiling_face: I managed to get the app running on my phone, after having had to open port 8081 on my firewall. But unfortunately something seems still off - I don't see any previous / next buttons :thinking: 
image

**Comment by wunmi-adb** [comment]
Great! please can you share this device name? I can try to test directly on it using an emulator. @simeoncarstens

**Comment by simeoncarstens** [comment]
@theresasogunle that would be amazing! :slightly_smiling_face: It's an Oppo Find X2 Lite, with up-to-date ColorOS.

**Comment by wunmi-adb** [comment]
@simeoncarstens I moved the buttons to the top :-) just to see if you can still see it. I tried it on several android emulators and the buttons were there, but i did notice a white section under the image added by your device, which could be responsible for that, so just to confirm that assumption, I moved the buttons to the top. If this is the case, i will find a fix for your device type.

**Comment by wunmi-adb** [comment]
So, please check again and please let me know :-)

**Comment by simeoncarstens** [comment]
@theresasogunle still no trace of the buttons :slightly_frowning_face: but if it works fine on emulators, it could just as well be a problem specific to my device. So I'd be happy to merge this as is, too :slightly_smiling_face:

**Comment by wunmi-adb** [comment]
@simeoncarstens  https://snack.expo.dev/@wumz/image-transition?platform=ios I have a created an Expo snack here that pretty much makes the code open source and can be tested on both android and IOS

**Comment by simeoncarstens** [comment]
It seems to work well on the Snack :slightly_smiling_face: I'd suggest you put a link to the Snack in the README (and why not into the blog post!) and then we can merge this PR as is :slightly_smiling_face:

**Comment by wunmi-adb** [comment]
@simeoncarstens I have done that, also added the link to the blog post itself.

**Review by simeoncarstens — APPROVED** [review]
:tada:

**Pull request merged**
